language: python
python:
  - "3.5"
install:
  - pip install -r geoserver-shell/requirements.txt
notifications:
  email:
    - cdval13@freeuni.edu.ge
services:
  - docker
before_install:
  - docker image build geoserver-shell/ -t publish
  - docker-compose up