version: '2.1'
services:

  postgis:
    image: openmaptiles/postgis
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=shareloc
     - POSTGRES_USER=shareloc
     - POSTGRES_DB=shareloc

  geoserver:
    image: kartoza/geoserver
    ports:
     - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/rest"]
      interval: 1s
      timeout: 1s
      retries: 60

  layer_publisher:
    image: publish
    depends_on:
      geoserver:
        condition: service_healthy

  flask_app:
    image: flaskapp
    ports:
      - 8000:8000